# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI_CD_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.17.1'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: cd pjt_front_react && npm install
    - run: cd pjt_front_react && npm run build
    - name: Deploy FE-server1
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd SSEKER/pjt_front_react/
          git pull
          ls -al
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm --version
          npm install
          npm run build
          pm2 start npm -- start
          sudo systemctl restart nginx
        host: ${{ secrets.AWS_TEST_X_HOST }}
        user: ${{ secrets.AWS_TEST_X_USERNAME }}
        key: ${{ secrets.AWS_TEST_X_KEY }}
    - name: Deploy FE-server2
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd SSEKER/pjt_front_react/
          git pull
          ls -al
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm --version
          npm install
          npm run build
          pm2 start npm -- start
  
        host: ${{ secrets.AWS_TEST_X_HOST_FE2 }}
        user: ${{ secrets.AWS_TEST_X_USERNAME }}
        key: ${{ secrets.AWS_TEST_X_KEY_FE2 }}